In [1]:
import numpy as np
import numba

In [2]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [83]:
class Board:
    def __init__(self, size):
        # Initialize the board
        self.size = size
        self.state = np.zeros((size,size))
        #Turn 1 is X, -1 is O
        self.turn = 1
    
    def get_state(self):
        return self.state
    
    def get_turn(self):
        return self.turn
    
    """
    Make a move for the player
    
        Parameters:
            player: The player to make the move where X is represented by 1 and O by -1
            move: The move to make in the format (row, column)
    """
    def make_move(self, player, move):
        #Check if move is valid
        if self.state[move] != 0 or self.turn != player:
            print("Invalid move")
            return
        #Make move
        self.state[move] = player
        #Change turn
        self.turn *= -1
    
    def __repr__(self) -> str:
        out = "⏤"*(self.size*2) + "\n"
        for i in range(self.size):
            out+= "⏐".join(self.state[i].tolist()) + "\n"
            out+= "⏤"*(self.size*2) + "\n"
        return out
        

In [84]:
b = Board(3)

In [85]:
b.get_state()

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [86]:
b.make_move(1,(1,1))

In [87]:
b.get_state()

array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.]])

In [88]:
b.make_move(-1,(1,1))

Invalid move


In [89]:
b.make_move(1,(1,2))

Invalid move


In [90]:
b.make_move(-1,(2,1))

In [91]:
b

TypeError: sequence item 0: expected str instance, float found